version: "3.9"
services:
  grpc:
    build:
      context: .
      args:
        BUILD_TARGET_PATH: ./cmd/grpc/todo/server/main.go
      target: grpc-server
    ports:
      - "50051:50051"
  openapi:
    build:
      context: .
      args:
        BUILD_TARGET_PATH: ./cmd/openapi/todo/server/main.go
      target: application
    environment:
      PORT: "3000"
    ports:
      - "3000:3000"
  graphql:
    build:
      context: .
      args:
        BUILD_TARGET_PATH: ./cmd/graphql/todo/server/server.go
      target: application
    ports:
      - "8080:8080"
